### ISSUE TITLE
Legacy Handbrake Profile

### ISSUE THREAD

**Issue by chaircommander** [automatic-ripping-machine/automatic-ripping-machine#282] opened 2019-01-26 11:24 UTC
### Description
Within the arm.yaml config file, it still has "High Profile" as the default profile for HandBrake which is no longer supported. HandBrake.fr suggests to use the comparable "HQ 1080p30 Surround" instead. This fixed handbrake reporting invalid profile in the error logs.

**Comment by ahnooie** [comment] 2019-01-26 16:31
Thanks, this is a duplicate of #271 and will be fixed in the next release.

**Closed by ahnooie** 2019-01-26 16:31 UTC
Labels: duplicate
