### ISSUE TITLE
🐛 Call to makemkv failed

### ISSUE THREAD

**Issue by devmon** [automatic-ripping-machine/automatic-ripping-machine#1215] opened 2024-10-12 05:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Blu ray ejects after call to makemkv fails. 

### To Reproduce

1. Using docker in debian 12 container in proxmox
2. Start arm container and insert blu ray

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

v.2.8.1

### Expected behavior?

Makemkv to start ripping blu ray

### Relevant log output

```shell
Loading log: LOTR_FELLOWSHIP_OF_THE_RING_P1_172870948292.log...
[10-12-2024 05:04:42] INFO ARM: ARM version: 2.8.1
[10-12-2024 05:04:42] INFO ARM: Python version: 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]
[10-12-2024 05:04:42] INFO ARM: User is: arm
[10-12-2024 05:04:42] INFO ARM: Alembic head is: b326a3663939
[10-12-2024 05:04:42] INFO ARM: Database version is: b326a3663939
[10-12-2024 05:04:42] INFO ARM: ************* Starting ARM processing at 2024-10-12 05:04:42.937479 *************
[10-12-2024 05:04:43] INFO ARM: Looking for log files older than 1 days old.
[10-12-2024 05:04:43] INFO ARM: Checking path /home/arm/logs/ for old log files...
[10-12-2024 05:04:43] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[10-12-2024 05:04:43] INFO ARM: Job: LOTR_FELLOWSHIP_OF_THE_RING_P1
[10-12-2024 05:04:43] INFO ARM: Job #9 with PID 1484 is currently running.
[10-12-2024 05:04:43] INFO ARM: Starting Disc identification
[10-12-2024 05:04:43] INFO ARM: Mounting disc to: /mnt/dev/sr0
[10-12-2024 05:04:45] INFO ARM: Mounting disc was successful
[10-12-2024 05:04:45] INFO ARM: Disc identified as video
[10-12-2024 05:04:45] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:46] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:46] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:46] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:46] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:47] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:47] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:47] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:47] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:48] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:48] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:48] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:48] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:48] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:49] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:49] ERROR ARM: omdb call failed with error - HTTP Error 401: Unauthorized
[10-12-2024 05:04:49] INFO ARM: Disc title Post ident -  title:The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 year:2020 video_type:unknown disctype: bluray
[10-12-2024 05:04:49] INFO ARM: We have no previous rips/jobs matching this label
[10-12-2024 05:04:49] INFO ARM: Waiting 60 seconds for manual override.
[10-12-2024 05:05:49] INFO ARM: ******************* Logging ARM variables *******************
[10-12-2024 05:05:49] INFO ARM: devpath: /dev/sr0
[10-12-2024 05:05:49] INFO ARM: mountpoint: /mnt/dev/sr0
[10-12-2024 05:05:49] INFO ARM: title: The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1
[10-12-2024 05:05:49] INFO ARM: year: 2020
[10-12-2024 05:05:49] INFO ARM: video_type: unknown
[10-12-2024 05:05:49] INFO ARM: hasnicetitle: False
[10-12-2024 05:05:49] INFO ARM: label: LOTR_FELLOWSHIP_OF_THE_RING_P1
[10-12-2024 05:05:49] INFO ARM: disctype: bluray
[10-12-2024 05:05:49] INFO ARM: ******************* End of ARM variables *******************
[10-12-2024 05:05:49] INFO ARM: ******************* Logging config parameters *******************
[10-12-2024 05:05:49] INFO ARM: skip_transcode: False
[10-12-2024 05:05:49] INFO ARM: mainfeature: 1
[10-12-2024 05:05:49] INFO ARM: minlength: 600
[10-12-2024 05:05:49] INFO ARM: maxlength: 99999
[10-12-2024 05:05:49] INFO ARM: videotype: auto
[10-12-2024 05:05:49] INFO ARM: manual_wait: True
[10-12-2024 05:05:49] INFO ARM: manual_wait_time: 60
[10-12-2024 05:05:49] INFO ARM: ripmethod: backup
[10-12-2024 05:05:49] INFO ARM: mkv_args: 
[10-12-2024 05:05:49] INFO ARM: delrawfiles: True
[10-12-2024 05:05:49] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[10-12-2024 05:05:49] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[10-12-2024 05:05:49] INFO ARM: hb_args_dvd: --subtitle scan -F
[10-12-2024 05:05:49] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[10-12-2024 05:05:49] INFO ARM: raw_path: /home/arm/media/raw/
[10-12-2024 05:05:49] INFO ARM: transcode_path: /home/arm/media/transcode/
[10-12-2024 05:05:49] INFO ARM: completed_path: /home/arm/media/completed/
[10-12-2024 05:05:49] INFO ARM: extras_sub: extras
[10-12-2024 05:05:49] INFO ARM: emby_refresh: False
[10-12-2024 05:05:49] INFO ARM: emby_server: 
[10-12-2024 05:05:49] INFO ARM: emby_port: 8096
[10-12-2024 05:05:49] INFO ARM: notify_rip: True
[10-12-2024 05:05:49] INFO ARM: notify_transcode: True
[10-12-2024 05:05:49] INFO ARM: max_concurrent_transcodes: 0
[10-12-2024 05:05:49] INFO ARM: ******************* End of config parameters *******************
[10-12-2024 05:05:49] INFO ARM: Checking for fstab entry.
[10-12-2024 05:05:49] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[10-12-2024 05:05:49] INFO ARM: Output directory "/home/arm/media/transcode/unidentified/The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 (2020)" already exists.
[10-12-2024 05:05:49] INFO ARM: Final Output directory "/home/arm/media/transcode/unidentified/The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 (2020)_172870948292"
[10-12-2024 05:05:49] INFO ARM: Output directory "/home/arm/media/completed/unidentified/The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 (2020)" already exists.
[10-12-2024 05:05:49] INFO ARM: Final Output directory "/home/arm/media/completed/unidentified/The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 (2020)_172870948292"
[10-12-2024 05:05:49] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/The-Lord-of-the-Rings--The-Fellowship-of-the-Ring-(EXT.)-PT.-1 (2020)_172870948292
[10-12-2024 05:05:49] INFO ARM: ************* Ripping disc with MakeMKV *************
[10-12-2024 05:05:49] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-WaI15n3jLrzWU88y7liOljd7UIR0mormcZo2oO5xt_9CSj3Mg6mOxR1eUvU_CA569e
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[10-12-2024 05:05:50] INFO ARM: Starting MakeMKV rip. Method is backup
[10-12-2024 05:05:50] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[10-12-2024 05:05:50] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[10-12-2024 05:05:50] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 213, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[10-12-2024 05:05:50] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

Tried to fix by changing makemkv mode from mkv to backup but same issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devmon** [comment] 2024-10-12 05:30
start_arm_container.sh
![Screenshot_20241012_012639_Chrome](https://github.com/user-attachments/assets/366a5c41-021a-4849-adcd-6a824653204d)

lsscsi -g output
![Screenshot_20241012_012913_Chrome](https://github.com/user-attachments/assets/fb1c38db-da01-4d14-bc43-73eccadc9985)

**Comment by microtechno9000** [comment] 2024-10-12 08:48
This is a known issue being worked on at the moment

Closing as a duplicate of #1195

**Closed by microtechno9000** 2024-10-12 08:48 UTC
Labels: bug
