### ISSUE TITLE
🐋 abcde.conf is only a symlink in the config directory

### ISSUE THREAD

**Issue by z4ch523** [automatic-ripping-machine/automatic-ripping-machine#749] opened 2023-02-21 20:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I mounted the config directory to a folder on the host like this:
` -v '/mnt/user/appdata/Automatic-Ripping-Machine/config':'/etc/arm/config':'rw'`

When I open the directory on the host machine I see 2 files apprise.yaml & arm.yaml as well as a symlink called abcde.conf.

### To Reproduce

Installed ARM as docker on an unRAID Host OS.
Mapp the config folder like this  -v 'YOUR-HOST-DIRECTORY':'/etc/arm/config':'rw'.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

There should be a 'real' file abcde.conf

### Anything else?

Was already mentioned in the discord channel by another user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment] 2023-02-23 02:15
I ran this down and my initial answer in the discord was wrong. `.abcde.conf` is indeed supposed to be in `/etc`, with a symlink to `/etc/arm/config/abcde.conf`. That is indeed the expected behavior. I don't know why you added the `:'rw'`, but it's unnecessary

**Comment by 1337-server** [comment] 2023-02-23 02:45
I dealt a lot with the Audio CD side of things. Just to clear things up.

abcde has default places to look for the .abcde.conf file it will try these
 /etc/abcde.conf and then $HOME/.abcde.conf

But because we wanted to set our own location (both for ui editing and end user ease of use) we pass in a config file here from the arm.yaml and if it exist abcde will use that config file and not the default:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/1047dfbdc049378ebdbe043c7b743cf23d40e345/arm/ripper/utils.py#L352-L357

the only reason it would check in the default places is if the one in the arm.yaml doesnt exist.
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/1047dfbdc049378ebdbe043c7b743cf23d40e345/setup/arm.yaml#L112

But if that were the case the UI would be broken.

**Comment by makuser** [comment] 2023-03-01 17:08
> .abcde.conf` is indeed supposed to be in `/etc`, with a symlink to `/etc/arm/config/abcde.conf`.

That would be fine, but it is the other way around.

```bash
root@ea79432a6d9a:~# ls /etc/arm/config/ /etc/.abcde.conf -alF
-rwxr-xr-x 1 arm arm 21567 Mar  1 16:51 /etc/.abcde.conf*

/etc/arm/config/:
total 36
drwxr-xr-x 1 arm  arm     90 Mar  1 17:06 ./
drwxr-xr-x 1 arm  arm     12 Mar  1 16:51 ../
lrwxrwxrwx 1 root root    16 Mar  1 17:06 abcde.conf -> /etc/.abcde.conf*
-rwxr-xr-x 1 arm  arm   4700 Aug 25  2022 apprise.yaml*
-rw-r--r-- 1 arm  arm  11407 Mar  1 11:11 arm_220301.yaml
-rw-r--r-- 1 arm  arm  11426 Mar  1 17:07 arm.yaml
root@ea79432a6d9a:~# 
```

**Comment by duckfullstop** [comment] 2023-03-01 17:13
Blaming #669 for this regression - this issue needs reopening (thanks for linking the two @makuser!).

The temporary workaround is to rename your `abcde.conf` to `abcde-persist.conf` or something similar, then change `ABCDE_CONFIG_FILE` in `arm.conf` appropriately.

**Comment by shitwolfymakes** [comment] 2023-03-01 17:24
> Blaming #669 for this regression - this issue needs reopening (thanks for linking the two @makuser!).
> 
> 
> 
> The temporary workaround is to rename your `abcde.conf` to `abcde-persist.conf` or something similar, then change `ABCDE_CONFIG_FILE` in `arm.conf` appropriately.

Confirmed. I got the paths swapped around in the new link command. Reopen this issue and I'll fix it

**Comment by microtechno9000** [comment] 2023-03-07 12:17
Still an issue, setting up docker has broken the abcde.conf

**Comment by noideas4thisname** [comment] 2023-06-21 01:49
Any chance we can remove the wontfix tag from this? I believe I'm being impacted by the same issue. I've found that when setting up the docker, the abcde config files get blown away with every docker update no matter where you have them specified (and it seems somewhat related). Even setting a custom path results in the abcde file being reset on docker update.

**Closed** 2023-09-24 21:43 UTC
Labels: bug, ABCDE
