### ISSUE TITLE
V2_master cannot rip while encoding.

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#210] opened 2018-07-15 23:45 UTC
Hi @muckngrind4 I have opened a new issue as requested. I am still unable to rip a dvd while one is currently processing, I have done a totally fresh install onto ubuntu 18.04 and the issue still remains. I have no idea what log files you will require or what you want me to try so just let me know.

**Comment by muckngrind4** [comment] 2018-07-17 06:45
Hi @Yokopops.  I'm going to do some testing to see if I can reproduce the issue in my environment.  I'll let you know what I find.

**Comment by ahnooie** [comment] 2018-07-18 05:45
This could be systemd.  Per https://www.freedesktop.org/software/systemd/man/systemd.service.html for the oneshot type "it is expected that the process has to exit before systemd starts follow-up units."  I'm testing changing the systemd service type from oneshot to simple which may allow multiple processes (but likely won't know if it is going to work until tomorrow).  v1 was using oneshot but that may have been okay because it was spawning off the process.

**Comment by muckngrind4** [comment] 2018-07-19 03:55
@Yokopops Testing and subitting issues is really helpful!  The nature of ARM means that it takes a long time to full test a code change, especially when there are so many config options.  Having testers is really helpful... 
If you want to test this you can. It's a simple change.  Edit the /etc/systemd/system/arm@.service file and change the line from "Type=oneshot" to "Type=simple",  Then see if the behavior changes.

**Comment by ahnooie** [comment] 2018-07-19 05:06
Well, Type=simple didn't work.  May have to try spawning off the process.  If spawning doesn't work it could also be the previous process is holding a lock on something, maybe the drive.

**Comment by muckngrind4** [comment] 2018-07-19 05:17
OK.  I was able to reproduce this.  I have two drives and they can rip/transcode simultaneously without issue.  This issue only occurs when using the same drive in succession. This is because ARM launches a service with the device name embedded in the service name.  So a disc in /dev/sr0 will launch a service named arm@sr0.service.  So maybe we can embed something else in the service name...such as the label name, or some randomized number?

**Comment by Yokopops** [comment] 2018-07-23 01:01
Any fix for this issue yet?

**Comment by muckngrind4** [comment] 2018-07-23 06:53
Close. I've tried lots of options and I don't think systemd will work. I'm testing a wrapper script now. Hopefully I'll have something to test in a day or two.

**Comment by Yokopops** [comment] 2018-07-23 17:14
Awesome, keep up the good work! In the meantime did you say if I plug in my external drive and then alternate between the two it will work?

**Comment by muckngrind4** [comment] 2018-07-25 04:57
Yes it should.  I have two internal drives and can use both at the same time without any issues.

**Comment by Yokopops** [comment] 2018-07-27 20:16
New thing I found. If you dont remove the disc from the drive in a set time it auto closes, unsure if this causes it to rerip or is programmed to auto close?

**Comment by muckngrind4** [comment] 2018-07-28 17:43
I've pushed a fix to v2_fixes.  @Yokopops  and @ahnooie Can you try it?  A couple of notes:
- This eliminates systemd and goes back to the old schools arm_wrapper.  So you'll need to make a few updates:
1) Update your symlink to 51-automedia.rules
2) Reload udev rules `sudo udevadm control --reload-rules`
3) Probably remove all traces of the systemd files.  See [this](https://superuser.com/questions/513159/how-to-remove-systemd-services) link.

Udev should now launch the arm_wrapper which in turn will launch ARM.  I've tested multiple rips across multiple drives and in sequence on a single drive and haven't seen and problems...yet...

Thanks.  Let me know how it goes.

**Comment by Yokopops** [comment] 2018-08-01 19:34
Will try this soon. Thanks

**Closed** 2018-08-06 00:13 UTC
Labels: bug

**Comment by Yokopops** [comment] 2018-08-07 22:06
Just got around to attempting to use this fix as I have been busy with work, however everything appears to be doing the same? Not sure if I screwed up a setting? i may have screwed the symlink up? Whats the command to use, the one in the guide "sudo ln -s /opt/arm/setup/51-automedia.rules /lib/udev/rules.d/"?

Kind regards

P.s Sorry it took so long to get around to testing this

**Comment by muckngrind4** [comment] 2018-08-08 05:53
Can you run "ps -aux|grep arm" when ARM is running and post back the results?

**Comment by Yokopops** [comment] 2018-08-08 18:49
root      1508  0.0  0.0  61968  3032 ?        S    19:43   0:00 /bin/systemctl start arm@sr0.service
arm       1509  3.2  0.6 104412 27476 ?        Ss   19:43   0:00 /usr/bin/python3 /opt/arm/arm/main.py -d sr0
arm       1533  0.0  0.0   4628   780 ?        S    19:43   0:00 /bin/sh -c makemkvcon mkv  -r dev:/dev/sr0 all /home/arm/media/raw/STEPTOE_AND_SON_SERIES_2 --minlength=600>> /home/arm/logs/STEPTOE_AND_SON_SERIES_2.log
arm       1534 77.3  0.4 1039156 19328 ?       Sl   19:43   0:16 makemkvcon mkv -r dev:/dev/sr0 all /home/arm/media/raw/STEPTOE_AND_SON_SERIES_2 --minlength=600
arm       1537  0.0  0.0      0     0 ?        ZN   19:43   0:00 [wget] <defunct>
arm       1538  0.0  0.0      0     0 ?        ZN   19:43   0:00 [wget] <defunct>

Getting the issue where it is not naming files and folders correctly again by the way, so will go back into my config and double check if its the config or my dvds not been found in the database, an example of a couple dvds are District 9 and Team America world police. It named the folder for Team America to 
"Team America - World Police" however the files are all named title00 to title02 and left it in the unidentified folder.

Kind regards

P.s Sorry for been a major pain in the ass...

**Comment by muckngrind4** [comment] 2018-08-10 04:18
It's definitely still running as arm.  Check and make sure the 51-automedia.rules file is pointing to arm_wrapper.sh and that the symlink is set up and pointing to the 51-automedia.rules file.  Finally run 'udevadm control --reload-rules'.  That should be all that is needed.

As for the naming incorrectly, open a new issue with the log file.  I'll need it to determine what path ARM took in order to track down where the naming issue is.  Don't worry about being "pain", it actually helps me track down all the issues.

**Comment by Yokopops** [comment] 2018-08-11 17:16
Just looked at it again and noticed I forgot to comment out the systemd line. Running it now and will report  back, was my fault entirely should have been more careful.

**Comment by Yokopops** [comment] 2018-08-11 17:55
@muckngrind4. Either i'm been totally dumb or I am missing the arm_wrapper.sh script. I cannot find it on my server with the find command I have also looked where the rules file points to ("/opt/arm/arm_wrapper.sh") and it is not there either. Sorry about this but i'm still learning linux

**Comment by Yokopops** [comment] 2018-08-11 19:04
Gone over everything twice and re downloaded the repo. Rips will not start at all now and everything is pointing to where it should be.

**Comment by Yokopops** [comment] 2018-08-11 19:48
Will rip if I manually start main.py

**Comment by muckngrind4** [comment] 2018-08-11 20:41
Glad it's working. "at" wasnt needed when it systemd was used. I've added it back to the readme but it's easy to miss. 

Fyi, an ARM session would not survive a power failure.

**Comment by Yokopops** [comment] 2018-08-11 20:46
I should have been clearer, would it break the encoding process list and stop it processing? Going to open the issue about naming now as I have just tried to rip the dukes of hazzard and the folder it has made for the RAW files is called "title_unknown"

**Comment by muckngrind4** [comment] 2018-08-11 21:29
Ahh..  I see what you're asking. It's still no, but I see what you mean.  Right now ARM doesn't have a way to pick up where it left off, it either finishes or must be started all over.
