### ISSUE TITLE
v2_fixes not naming folders/files when type=dvd and mainfeature is false

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#238] opened 2018-08-11 22:17 UTC
[THE_DUKES_OF_HAZZARD_UNSEEN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2280582/THE_DUKES_OF_HAZZARD_UNSEEN.log)
Opened as per request by @muckngrind4. Interesting thing, the folder was named "title_unknown" and the files to "title00" ect however the name of the log is as seen, unsure on what to look for in the log so will leave it to the people who do.

**Comment by muckngrind4** [comment] 2018-08-12 17:12
Hi @Yokopops, this is actually intended behavior.  I'll explain the logic.  Most blurays have a file named bdmt_eng.xml which holds the title name in it.  Without it ARM has no idea what the name of the title is, soit calls the video "title_unknown" and processes the disc as you've seen.  (More on this can be seen on this issue #213).  In your case, the disc label is relatively close to the title name, so it could be used to try to guess the title.  But label naming is wildly inconsistent so it's really problematic to try to programatically guess names off of just the label.  So, for right now, there isn't really a way for ARM to address this.  However, I'm building a web interface for ARM in the next version that will add the ability to override the title identification on the fly.  That should make this a lot easier to deal with...

**Comment by Yokopops** [comment] 2018-08-12 20:58
Ok, but this dvd is not a Blu-ray disc, however, it names the folder correctly if I place the dvd into my none Blu-ray drive but when I did that it never ripped the DVD. I will post up the log file as I believe it will merge the attempted rips from both drives into the one file so you may have a look. May be a disc issue but the log file may be of interest I guess

**Comment by Yokopops** [comment] 2018-08-12 22:08
[THE_DUKES_OF_HAZZARD_UNSEEN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2281384/THE_DUKES_OF_HAZZARD_UNSEEN.log)
This log has I believe 3 rips, when the rips encode it also seems to miss the first couple mins of the film. As I said, this is not a bluray disc, however, the first attempt was on a bluray drive and so was the last, the one that named the folder correctly but did not encode was the middle one on my removable drive.

**Comment by muckngrind4** [comment] 2018-08-14 06:14
Hi @Yokopops, this one doesn't make sense.  ARM should be calculating the CRC value and then queriing the windows media web service and it's not.  Is this the only disc you are having the issue on?  If so, I'd probably chalk it up to the disc...

**Comment by Yokopops** [comment] 2018-08-15 19:56
This is the only one I am having this issue to this extent with, however, none of my DVDs are naming (folders or files) so i'm not sure. Want another log file from another dvd?

**Comment by Yokopops** [comment] 2018-08-23 18:30
[PARANORMAL_ACTIVITY_2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2315699/PARANORMAL_ACTIVITY_2.log)
folder named to title_unknown, also I ripped men in black 3 and it named the folder the same, however, the actual video files named to Men_In_Black_3_t##.mkv. Sorry it took me so long to get back to you as we have had internet issues the past few days and have been unable to connect.

**Comment by muckngrind4** [comment] 2018-08-24 04:35
Can you check to see if pydvdid is installed?
`pip3 show pydvdid`

**Comment by Yokopops** [comment] 2018-08-24 18:03
Name: pydvdid
Version: 1.1
Summary: A pure Python implementation of the Windows API IDvdInfo2::GetDiscID method, as used by Windows Media Center to compute a 'practically unique' 64-bit CRC for metadata retrieval.
Home-page: https://github.com/sjwood/pydvdid
Author: Steve Wood
Author-email: octocat@nym.hush.com
License: Apache License 2.0
Location: /usr/

Guess this means its installed?

**Comment by muckngrind4** [comment] 2018-08-25 14:35
Yes, it's installed.  I'm going to add some error handling to the identification process and push it to v2_fixes (probably a week or two away).  I'll let you know when and it will help us get more specifics on how it's failing.

**Comment by Yokopops** [comment] 2018-08-25 17:10
Sure thing. Keep me posted!

**Comment by Yokopops** [comment] 2018-09-05 18:06
@muckngrind4 Any news?

**Comment by Yokopops** [comment] 2018-09-27 20:00
@muckngrind4 It's still not sorting and naming DVDs. Just got the new SOLO movie today on blu-ray and it is in the unidentified folder.

**Comment by muckngrind4** [comment] 2018-10-01 06:57
Hi @Yokopops. I've updated v2_fixes with a little more error handling,  Can you try that and post your log?

**Comment by Yokopops** [comment] 2018-10-01 22:33
[TRANSFORMERS_AGE_OF_EXTINCTION.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2435899/TRANSFORMERS_AGE_OF_EXTINCTION.log)
Here you go, as requested! (The Solo one fixed itself somehow, Guess because its blu-ray)

**Comment by muckngrind4** [comment] 2018-10-02 04:48
OK.  I found what's happening.  I think it's a simple fix.  I'll have something posted later tonight.

**Comment by muckngrind4** [comment] 2018-10-02 06:29
Hi @Yokopops.  I've pushed a fix to v2_fixes.  Can you update your branch and then try the transformers dvd again?

**Comment by Yokopops** [comment] 2018-10-03 19:19
[_District_9_.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2443464/_District_9_.log)
Seems to have cured it! However new issue.. The extras seem to encode correctly however the main movie is just a 3kb file. Did the same on another DVD will try rip the other and give you that log aswell.

**Comment by muckngrind4** [comment] 2018-10-07 23:52
I'm not sure what is happening here.  It's a handbrake issue, from what I can see.  Try running handbrake manually and see what happens.  

I'm going to close this issue since the original issue is fixed.  Feel free to open a new one issue if you need to.

**Closed by muckngrind4** 2018-10-07 23:52 UTC
Labels: bug
