### ISSUE TITLE
ARM works until after transcode then fails on copy

### ISSUE THREAD

**Issue by aiohdfgaiuhg** [automatic-ripping-machine/automatic-ripping-machine#717] opened 2023-02-09 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

ARM works as expected when DVD inserted, DVD recognized, MKV deposited in raw folder, transcode starts as expected, transcoded mp4 is being created as expected in the transcode folder, then handbrake complete, and then ARM encounters a fatal error when trying to copy the completed mp4 to the completed directory.  

Permissions are set appropriately in the output directory as the folder within which I expect to see the completed files was created by arm and the transcode and raw directories are in the same overall directory and are written to as expected. 

![Screenshot 2023-02-09 at 11 37 20 AM](https://user-images.githubusercontent.com/122627690/217878498-b443de33-3834-4d8d-8255-b9d74c38c3fa.png)

I have in the ARM settings DEST_EXT listed as mp4
I also have delete raw files as True, which causes issues as then I loose everything - the script can't copy but can sure delete the files after the unsuccessful copy. 

Here is an example log:

"Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)[10:10:53] work: average encoding speed for job is 6.935702 fps

Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)[10:10:53] comb detect: heavy 11982 | light 4895 | uncombed 25846 | total 42723
[10:10:53] decomb: deinterlaced 11982 | blended 4895 | unfiltered 25846 | total 42723
[10:10:53] vfr: 42723 frames output, 0 dropped and 0 duped for CFR/PFR
[10:10:53] vfr: lost time: 0 (0 frames)
[10:10:53] vfr: gained time: 0 (0 frames) (0 not accounted for)
[10:10:53] ac3-decoder done: 44548 frames, 0 decoder errors
[10:10:53] mpeg2video-decoder done: 42723 frames, 0 decoder errors
[10:10:53] sync: got 42723 frames, 42723 expected
[10:10:53] sync: framerate min 29.970 fps, max 29.970 fps, avg 29.970 fps

Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)x265 [info]: frame I:    348, Avg QP:14.24  kb/s: 14217.63
x265 [info]: frame P:  12196, Avg QP:15.82  kb/s: 4773.43 
x265 [info]: frame B:  30179, Avg QP:23.36  kb/s: 983.67  
x265 [info]: Weighted P-Frames: Y:2.8% UV:1.6%
x265 [info]: consecutive B-frames: 13.0% 8.0% 34.1% 15.5% 29.5% 

encoded 42723 frames in 6170.64s (6.92 fps), 2173.32 kb/s, Avg QP:21.13
[10:10:53] mux: track 0, 42723 frames, 387435917 bytes, 2174.23 kbps, fifo 2048
[10:10:53] mux: track 1, 66823 frames, 28582133 bytes, 160.40 kbps, fifo 4096
[10:10:53] Finished work at: Thu Feb  9 10:10:53 2023

[10:10:53] libhb: work result = 0

Encode done!
HandBrake has exited.

[02-09-2023 10:10:54] INFO ARM: Handbrake processing complete
[02-09-2023 10:10:54] INFO ARM: ************* Finished Transcode With HandBrake *************
[02-09-2023 10:12:29] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details."

### To Reproduce

Insert Disc, wait for arm to transcode, finish transcode and then fails

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.12

### Expected behavior?

I expect the transcoded files to be copied to the completed folder

### Relevant log output

```shell
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)
Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)[10:10:53] work: average encoding speed for job is 6.935702 fps

Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)[10:10:53] comb detect: heavy 11982 | light 4895 | uncombed 25846 | total 42723
[10:10:53] decomb: deinterlaced 11982 | blended 4895 | unfiltered 25846 | total 42723
[10:10:53] vfr: 42723 frames output, 0 dropped and 0 duped for CFR/PFR
[10:10:53] vfr: lost time: 0 (0 frames)
[10:10:53] vfr: gained time: 0 (0 frames) (0 not accounted for)
[10:10:53] ac3-decoder done: 44548 frames, 0 decoder errors
[10:10:53] mpeg2video-decoder done: 42723 frames, 0 decoder errors
[10:10:53] sync: got 42723 frames, 42723 expected
[10:10:53] sync: framerate min 29.970 fps, max 29.970 fps, avg 29.970 fps

Encoding: task 1 of 1, 99.91 % (10.52 fps, avg 6.94 fps, ETA 00h00m06s)x265 [info]: frame I:    348, Avg QP:14.24  kb/s: 14217.63
x265 [info]: frame P:  12196, Avg QP:15.82  kb/s: 4773.43 
x265 [info]: frame B:  30179, Avg QP:23.36  kb/s: 983.67  
x265 [info]: Weighted P-Frames: Y:2.8% UV:1.6%
x265 [info]: consecutive B-frames: 13.0% 8.0% 34.1% 15.5% 29.5% 

encoded 42723 frames in 6170.64s (6.92 fps), 2173.32 kb/s, Avg QP:21.13
[10:10:53] mux: track 0, 42723 frames, 387435917 bytes, 2174.23 kbps, fifo 2048
[10:10:53] mux: track 1, 66823 frames, 28582133 bytes, 160.40 kbps, fifo 4096
[10:10:53] Finished work at: Thu Feb  9 10:10:53 2023

[10:10:53] libhb: work result = 0

Encode done!
HandBrake has exited.

[02-09-2023 10:10:54] INFO ARM: Handbrake processing complete
[02-09-2023 10:10:54] INFO ARM: ************* Finished Transcode With HandBrake *************
[02-09-2023 10:12:29] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aiohdfgaiuhg** [comment] 2023-02-09 16:47
There is no more to the log file - that's the end of it

**Comment by 1337-server** [comment] 2023-02-09 17:51
I believe this is a duplicate of https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/606

It's caused by the final move files not accounting for file types other than `mkv`
You can confirm this by Running the disc again in DEBUG mode and the output should be the same as here

https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/606#issuecomment-1423373843

If not, let me know and ill re-open the issue.

**Closed by 1337-server** 2023-02-09 17:51 UTC
Labels: bug, duplicate

**Comment by aiohdfgaiuhg** [comment] 2023-02-09 17:54
Looks to be the same - I take it the other issue will remain open until fix?

Would a work around right now be just listing destination extension as mkv until script updated?  Thanks for the help and work on script.

**Comment by 1337-server** [comment] 2023-02-09 17:58
Yes, the other issue will stay open until a PR is merged to fix it.

Using the `mkv` extension should work fine until the issue is resolved/closed.

**Comment by aiohdfgaiuhg** [comment] 2023-02-09 17:58
Thanks

**Comment by theRealBassist** [comment] 2023-04-28 18:14
Hello!

I seem to be experiencing this same issue? I have read through the thread for #606  and #756 and I seem to still be experiencing that issue while running on version 2.6.29. specifically the docker version. Permissions are 777 across the entire ARM home directory, and it doesn't seem to have problems making folders, just moving them. I'll include an example log below. I may have just missed something stupidly obvious, but it had been working fine up until about a week ago following some updates.

[DVD_VIDEO.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/11356241/DVD_VIDEO.log)
