### ISSUE TITLE
🐋 Unable to rip movies on Unraid in docker

### ISSUE THREAD

**Issue by TimVanDyke** [automatic-ripping-machine/automatic-ripping-machine#1044] opened 2024-01-23 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After installing and setting up the docker image I am unable to rip movies. It DOES try, it spins up the disk and recognizes it. It attempts a rip, and then does nothing. 

The jobs hang, I cannot abandon old jobs from the webUI. When I attempt to it says they cannot be found. and then the webui sometimes crashes or something when I'm trying to look at the logs there. 

### To Reproduce

In UnRaid with the most recent container with the NVIDIA driver installed and patched and recognized in the ARM rips do not rip. 

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

the rips rip

### Relevant log output

```shell
Here's a few relevant logs: 
Attempting a troubleshooting step from the FAQ
 
# su arm
arm@9f214b6b54d0:~$ /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
[2024-01-23 15:28:36,589] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-01-23 15:28:36,658] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-01-23 15:28:36,675] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2024-01-23 15:28:36,675] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2024-01-23 15:28:36,677] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x14a82f705f40>) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) (save_remote_images=True) (language=en) (id=1) (database_limit=200) 
[2024-01-23 15:28:36,678] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2024-01-23 15:28:36,679] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2024-01-23 15:28:36,679] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2024-01-23 15:28:36,679] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x14a82f705f40>) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) (save_remote_images=True) (language=en) (id=1) (database_limit=200) 
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: DEVLINKS: /dev/disk/by-id/usb-hp_CDDVDW_SN-208DB_5238593636474E4341303057-0:0 /dev/cdrom /dev/disk/by-label/BARBIE_STAR_LIGHT_ADVENTURE /dev/disk/by-path/pci-0000:01:00.0-usb-0:4:1.0-scsi-0:0:0:0 /dev/cdrw /dev/disk/by-uuid/48fd922400000000 /dev/dvd /dev/dvdrw
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: DEVNAME: /dev/sr0
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: DEVPATH: /devices/pci0000:00/0000:00:01.3/0000:01:00.0/usb1/1-4/1-4:1.0/host0/target0:0:0/0:0:0:0/block/sr0
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: DEVTYPE: disk
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: DISKSEQ: 22
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_BUS: usb
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD_R: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD_RW: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_R: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_RW: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_R_DL: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_R: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_RAM: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_RW: 1
[2024-01-23 15:28:36,704] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_DVD: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_SESSION_COUNT: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_STATE: complete
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_TRACK_COUNT: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_TRACK_COUNT_DATA: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MRW: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MRW_W: 1
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FOR_SEAT: block-pci-0000_01_00_0-usb-0_4_1_0-scsi-0_0_0_0
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_LABEL: BARBIE_STAR_LIGHT_ADVENTURE
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_LABEL_ENC: BARBIE_STAR_LIGHT_ADVENTURE
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_TYPE: udf
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_USAGE: filesystem
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_UUID: 48fd922400000000
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_UUID_ENC: 48fd922400000000
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_FS_VERSION: 1.02
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_INSTANCE: 0:0
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_MODEL: CDDVDW_SN-208DB
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_MODEL_ENC: CDDVDW\x20SN-208DB\x20
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_MODEL_ID: 0840
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_PATH: pci-0000:01:00.0-usb-0:4:1.0-scsi-0:0:0:0
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_PATH_TAG: pci-0000_01_00_0-usb-0_4_1_0-scsi-0_0_0_0
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_REVISION: HH01
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_SERIAL: hp_CDDVDW_SN-208DB_5238593636474E4341303057-0:0
[2024-01-23 15:28:36,705] DEBUG ARM: job.parse_udev pyudev: ID_SERIAL_SHORT: 5238593636474E4341303057
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_TYPE: cd
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_USB_DRIVER: usb-storage
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_USB_INTERFACES: :080250:
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_USB_INTERFACE_NUM: 00
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR: hp
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR_ENC: hp\x20\x20\x20\x20\x20\x20
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR_ID: 13fd
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: MAJOR: 11
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: MINOR: 0
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: SUBSYSTEM: block
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: SYSTEMD_MOUNT_DEVICE_BOUND: 1
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: TAGS: :uaccess:seat:systemd:
[2024-01-23 15:28:36,706] DEBUG ARM: job.parse_udev pyudev: USEC_INITIALIZED: 1995007316
-9 days, 14:21:48.535571
-9 days, 22:11:34.826250
-9 days, 23:48:41.096059
-1 day, 23:42:02.656027
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 186, in <module>
    drive_utils.update_drive_job(job)
  File "/opt/arm/arm/ui/settings/DriveUtils.py", line 152, in update_drive_job
    drive.new_job(job.job_id)
AttributeError: 'NoneType' object has no attribute 'new_job'
arm@9f214b6b54d0:~$ 
```

Here's what happens when I attempt a rip in every case:
``` 

[01-15-2024 13:40:11] INFO ARM: ARM version: 2.6.67
[01-15-2024 13:40:11] INFO ARM: Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
[01-15-2024 13:40:11] INFO ARM: User is: arm
[01-15-2024 13:40:11] INFO ARM: Alembic head is: 469d88477c13
[01-15-2024 13:40:11] INFO ARM: Database version is: 469d88477c13
[01-15-2024 13:40:11] INFO ARM: ************* Starting ARM processing at 2024-01-15 13:40:11.565606 *************
```
```


### Anything else?

Let me know if you need anything, I'm around in the discord. I'm happy to give more info but I don't know enough about the project yet to know what you need

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment] 2024-01-23 21:14
This is a duplicate of an existing issue (988), the job fails due to a field missing data. A PR is in works to resolve this issue #1025

**Closed by microtechno9000** 2024-01-23 21:14 UTC
Labels: bug

**Comment by TimVanDyke** [comment] 2024-01-24 00:42
Thank you, sorry for the duplicate
