### ISSUE TITLE
Folders and Rips in 'completed' are replaced when identical name was detected

### ISSUE THREAD

**Issue by newhinton** [automatic-ripping-machine/automatic-ripping-machine#505] opened 2022-05-28 15:42 UTC
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
When a dvd is inserted and has a name that was already ripped, the output is replaced in the completed-folder.

Some used parameters: 
```
SKIP_TRANSCODE: true
GET_VIDEO_TITLE: true
ALLOW_DUPLICATES: true
```
I would expect that `ALLOW_DUPLICATES` would always prepend a timestamp to any created folder, but that seems not to be the case.

**To Reproduce**
1. Insert CD and rip
2. See content on disk, replace existing ripped file with an empty one
3. Insert CD again
4. See that the empty file has been recreated again

### Environment
Ubuntu 20.04
f4496dab18181171eb072e35787b1031185d4af5

### Log file

[F3_37871_SE(1).log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8791399/F3_37871_SE.1.log)

**Comment by 1337-server** [comment] 2022-05-28 23:33
**Confirmed**
---
A.R.M does create the directory 

`DEBUG ARM: utils.make_dir Creating directory: /mnt/Serien2/Rips/transcode/unidentified/F3_37871_SE_165374003379`


Thanks for reporting!

But this ignores this
`utils.move_files Moving 'title_t04.mkv' to /mnt/Serien2/Rips/completed/unidentified/F3_37871_SE/extras`

**Comment by newhinton** [comment] 2022-05-29 04:53
is there a quick way to 'fix'this? 

I have tried adding timestamps to the discname, but that just broke everything and was ignored anyway.


if not i'll probably write a small script to move around my files when created

**Comment by 1337-server** [comment] 2022-05-30 01:03
I don't have a quick fix right now, but if you want to look at this yourself, inside `arm/ripper/utils.py` you will be looking for the function `move_files`. It deals with the final move and path generation.

The reason I don't have a quick fix is that I think this may already be fixed in my own repo, and I am waiting for more testing before I merge to the main repo.

**Comment by xinafoid** [comment] 2022-06-01 08:23
Could probably comment out the delete_raw_files definition so you have a backup after the mkv rip, especially if you are not transcoding, ultimately leaving you with 2 file locations (/completed and /raw). So if the one in /completed gets wiped you have the other. Or I see that in the "move_files_main" definition, it has a conditional that prevents the file from moving in the first place, leaving it in the /raw folder that's just going to get deleted from the previous statement. Either could A) write another conditional that force creates a parent directory with "Folder Name (n+1)" in /completed and puts the mkv in there, or B) create a constant equal to the number 0 and if there the file is in there, i.e.

> (logging.info(f"File: {new_file} already exists.  Not moving.")

...then the constant would change to "1", and carry over into the first mentioned "delete_raw_files", that would skip if constant is not equal to 0.

Idk thought it would be fun to take a wack at it, haven't coded in years and I appreciate all the hard work you all do to keep this project alive.

**Closed** 2022-06-05 03:23 UTC
Labels: bug
