### ISSUE TITLE
Trailing space in logfile name

### ISSUE THREAD

**Issue by bwarden** [automatic-ripping-machine/automatic-ripping-machine#452] opened 2021-09-09 20:55 UTC
Logfile name generation adds a trailing space after ".log", resulting in two files used for logging (e.g. `foo.log` and `foo.log `), the latter of which is not reaped by the date-based cleanup.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/851db6f4862a3872702a64e5467a853cca0d058d/arm/ripper/logger.py#L45

**Comment by microtechno9000** [comment] 2021-09-15 12:26
bwarden this is a duplicate of #445

**Closed** 2022-04-29 04:03 UTC
Labels: duplicate
