### ISSUE TITLE
🔧 Continue from last incomplete task

### ISSUE THREAD

**Issue by ThePianoMan2255** [automatic-ripping-machine/automatic-ripping-machine#922] opened 2023-08-29 14:16 UTC
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

When there is a power outage it appears there is no respectable queue to continue off of. 

### Describe the solution you'd like?

A queue that continues if incomplete, if a power outage or crash happens during a transcode it attempts to overwrite / redo the transcode that did not finish. Also it should continue the queue you had before the power outage occurred. 

### Describe alternatives you've considered?

Handbrake docker has a watcher which watches a folder and continues the transcodes if its found it was never deleted from a complete task. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment] 2024-01-20 08:07
Duplicate of #826

**Closed by 1337-server** 2024-01-20 08:07 UTC
Labels: enhancement
