### ISSUE TITLE
Blu-Ray looping conversion

### ISSUE THREAD

**Issue by gbirdsong** [automatic-ripping-machine/automatic-ripping-machine#229] opened 2018-08-02 19:37 UTC
### Description
[Description of Bug, Feature, Question, etc.]
Blu-Ray looping during conversion. Any fix for this?
### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
Ubuntu 16.04
### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by gbirdsong** [comment] 2018-08-03 00:39
[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2255591/empty.log)

**Comment by muckngrind4** [comment] 2018-08-03 05:06
It looks like something is killing your running process and triggering ARM to start again.  This might be sytemd (see 1st note below).   A couple of questions/suggestions:
- Are you on v2_master or v2_fixes?  If v2_fixes are you running the lastest version that uses the arm_wrapper script, or systemd?  Systemd causes some funny business and that might be the cause of the 1st process stoping and triggering a restart.
- Try changing MAINFEATURE to True in your config and see if it completes successfully
- Try changing RIPMETHOD to "mkv" and see how it goes.

One thing of note is that Handbrake has identified 394 titles and is trying to rip all of them over 600 seconds.  So even it it didn't restart, it probably be running for days or even weeks (it looks like it ran around 18 hours before restarting and was only through tile 20 of 394).

**Comment by gbirdsong** [comment] 2018-08-03 05:10
Not sure I will admit my skill are weak I am going to say V2_Master I couldn't exactly figure out how to convert. So is it normal for Handbrake to take this long? I'll boot that VM try it again Actully in process of creating V1 see if it works still.

**Comment by gbirdsong** [comment] 2018-08-03 05:38
Also DVD Drive seems to want to lock not open.

**Comment by gbirdsong** [comment] 2018-08-03 06:26
Thank you so much. Are these only two commands we run?

Or do I have to do something else in the instructions

**Comment by muckngrind4** [comment] 2018-08-03 06:37
That should be enough.   Full instructions are under the "Note if upgrading" section on the v2_fixes page here:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/v2_fixes

**Comment by gbirdsong** [comment] 2018-08-03 06:39
Thank you sir.  I saw this page when I try a lot of the steps it tells me so and so has already been completed or file exist.

Thank you so much for helping me.

**Comment by muckngrind4** [comment] 2018-08-11 16:55
Note: v2_fixes is now merged into v2_master...

**Closed by muckngrind4** 2018-08-11 16:55 UTC
