### ISSUE TITLE
Docker Startup error

### ISSUE THREAD

**Issue by Bestest-Coder** [automatic-ripping-machine/automatic-ripping-machine#1019] opened 2023-12-21 20:45 UTC
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/20e3ac86b7a84870d7f23a60921c91468edca063/scripts/docker/runit/arm_user_files_setup.sh#L70C4-L70C4

I think this line needs to be either `-rf` or check that `/home/arm/music` exists, because it currently fails as `rm -f` does not work on directories and cannot be worked around by directly making a volume at `/home/arm/Music`

**Comment by pweinrich3** [comment] 2023-12-23 00:17
Having the same issue. Tested on a brand new Ubuntu 20.04 VM with the latest updates and followed the wiki instructions. Receiving this error: 

```
Dec 22 23:34:17 2b53d3cb5526 syslog-ng[11]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 22 23:34:18 2b53d3cb5526 syslog-ng[11]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
rm: cannot remove '/home/arm/music': Is a directory
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
```

**Comment by sdight** [comment] 2023-12-27 20:00
I changed line 70 of to rm -rf and it solved the issue.

**Comment by Poweruser7** [comment] 2023-12-28 11:53
@sdight how did you do that? I assume you built de image locally. Or is there a easier way?

**Comment by microtechno9000** [comment] 2023-12-28 21:33
Replicated the issue, and changing the rm to an rm -rf solves the issue

**Comment by speedythesnail** [comment] 2023-12-30 20:05
I can't wait for #1025 to be merged, thanks for the work! 

I just discovered ARM this week and immediate ran into this issue. 

@Poweruser7 
I resolved this issue by editing the script and mounting it as a volume in my docker-compose file, rather than building a new image:
You can just pass it as an option to docker if you don't want to use compose, but I prefer compose over a docker run command.

Sample of my docker-compose.yaml file:
```
version: '3.8'
services:
  arm-rippers:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ARM_UID: 1001
      ARM_GID: 1002
    volumes:
      - '/media/arm/home:/home/arm'
      - '/media/arm/etc-config:/etc/arm/config'
      - '/media/arm/arm_user_files_setup.sh:/etc/my_init.d/arm_user_files_setup.sh'
    cpuset: '0,1,2,3,4,5'
```

Sometime this year I'd love to contribute to this project, I'll probably provide a sample Docker compose file that supports HTTPS with either your own certificate, or LetsEncrypt, using jwilder's nginx reverse proxy.

**Comment by thertzelle** [comment] 2024-01-28 04:13
I did a brand new install from the docker pre-build images tonight, and getting this error. As a newbie, this is a terrible start and error that i had to track down.

**Comment by microtechno9000** [comment] 2024-01-28 04:18
Agree, there is a patch in work to resolve this

**Comment by thertzelle** [comment] 2024-01-28 16:07
Is there a recommended docker version that works? Even after I patched the rm -rf issue, i got tons of python errors?

**Comment by microtechno9000** [comment] 2024-01-28 20:23
No specific docker version is required.

What errors are you seeing, if you post the output here I can see where the issue is

**Comment by Seserie** [comment] 2024-01-29 08:22
I have had this issue every time I have tried starting my own ARM docker container and it is really getting on my nerves that it hasn't been fixed. Here are the errors I get on the logs, it just keeps repeating and repeating over and over. I have had success with the solution listed by @speedythesnail above but for newbies it isn't the easiest to implement:

*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
rm: cannot remove '/home/arm/music': Is a directory
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
Jan 29 08:15:35 683a30e5831b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
Jan 29 08:16:27 683a30e5831b syslog-ng[12]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
rm: cannot remove '/home/arm/music': Is a directory
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
Jan 29 08:16:28 683a30e5831b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'

**Comment by microtechno9000** [comment] 2024-01-29 08:28
Agree, that issue has been resolved in a PR awaiting review
I pill ping the other devs to get it reviewed and out to all

**Closed** 2024-01-29 17:38 UTC
Labels: Docker, Bugfix
