### ISSUE TITLE
armui memory usage with giant log file

### ISSUE THREAD

**Issue by garbled1** [automatic-ripping-machine/automatic-ripping-machine#559] opened 2022-08-26 15:09 UTC
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
I had a BR go bad recently, and it produced an insanely large logfile filled with errors.  This caused armui to consume insane amounts of ram, get oom-killed, and then restarted repeatedly, until I finally killed it down.

Maybe some kind of sanity check to not process a log file over say 40MB?  Dunno?  BR's tend to be around 25MB on average.

**To Reproduce**
1. Stick a broken BR in that generates a 500MB log file.
2. Wait.

### Environment
Debian Bullseye
commit f4496dab18181171eb072e35787b1031185d4af5 (HEAD -> v2_master, origin/v2_master, origin/HEAD)

### Log file
*way too big*

**Comment by 1337-server** [comment] 2022-09-06 21:18
Dupe of #501

Update to latest version should resolve this issue.

**Closed by 1337-server** 2022-09-06 21:18 UTC
Labels: duplicate
