### ISSUE TITLE
TypeError: Query.paginate() takes 1 positional argument but 4 were given (Flask-SQLAlchemy)

### ISSUE THREAD

**Issue by andersix** [automatic-ripping-machine/automatic-ripping-machine#619] opened 2022-11-20 20:17 UTC
- [ X] I have checked the wiki
- [ X] I have searched for similar issues

**Describe the bug**
requirements.txt has "flask-sqlalchemy>=2.3.2", but if you get v3.0 or greater ARM fails because as of Flask-SQLAlchemy 3.0, all arguments to paginate are keyword-only.

**To Reproduce**
1. pip install -r requirements.txt

**Interim solution**
In requirements.txt, change to "flask-sqlalchemy<3.0" and downgrade/re-install it.

### Environment
Linux, but not OS related.

### Log file
(Note: I'm running ARM in a python3 virtual environment)
```
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/arm/.venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/arm/arm/../arm/ui/routes.py", line 228, in database
    jobs = Job.query.order_by(db.desc(Job.job_id)).paginate(page, 100, False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
```

**Comment by JaxJaxW** [comment] 2022-11-21 06:40
Just ran into this using a fresh install with ubuntu-20.04-install.sh on ARM 2.6.0. Fixed it as andersix said by changing the requirements.txt, downgrading to flask-sqlalchemy-2.5.1, and restarting the armui service.

It broke a number of pages of the ARM UI and didn't allow me to run rips. This also breaks the `sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0` command with this as the feedback:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 443, in <module>
    running_jobs = db.session.query(Job).filter(Job.status.notin_(['fail', 'success']), Job.devpath == devpath).all()
  File "<string>", line 2, in query
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

**Comment by wScottSh** [comment] 2022-11-26 19:24
Adding my voice to the mix. Same as @JaxJaxW

**Comment by shitwolfymakes** [comment] 2022-11-30 18:46
Please ensure that none of you are running ARM on Ubuntu 22.x. We've been getting a lot of weird breakages and support is not yet being provided for it.

As for next steps, try running the ubuntu installer with the `-d` flag. This will install the development stack and includes the latest version of ARM (v2.6.8). After that, run the following to enable the udev rules (the development installation skips this step):
```
sudo cp /opt/arm/setup/51-automedia.rules /etc/udev/rules.d/
sudo udevadm control --reload
```

At present, the installer doesn't have a way to specify installing the latest tag. It either installs the latest *release* tag (v2.6.1 through v2.6.8 are pre-release tags) or the dev branch. I'll add that to the To-Do list

**Comment by wScottSh** [comment] 2022-12-03 22:05
Yup, looks like I'm running v22.04. My mistake. Reinstalling the OS down to 20.04. Will report back here if that fixes my issue.

**Comment by speedtoys** [comment] 2022-12-15 02:52
This fixed my Ubuntu 20.04 issues as well.

**Comment by fbermel** [comment] 2023-01-04 08:28
I've opened a duplicate of this on accident. I've described a proper solution to this issue that doesn't involve downgrading your OS.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/641

**Comment by 1337-server** [comment] 2023-02-03 08:43
> I've opened a duplicate of this on accident. I've described a proper solution to this issue that doesn't involve downgrading your OS.
> 
> #641

Just tested this and you are correct. ARM (v2_devel branch) does work on Ubuntu 22. It's the script installer that is broken for it.

The issue is with the repo `sudo add-apt-repository ppa:mc3man/focal6 -y` and the package `python3-psutil`
removing or ignoring both these requirements allows ARM to be installed and the ripper to work correctly.

The only negative consequence I have noted so far is that it stops both the CPU usage and Memory usage from showing in the UI

**Comment by 1337-server** [comment] 2023-02-23 04:29
Closing as this is now fixed.

**Closed by 1337-server** 2023-02-23 04:29 UTC
Labels: bug, Python
