### ISSUE TITLE
If DVD has a title use it instead of title name from identification

### ISSUE THREAD

**Issue by sphaero** [automatic-ripping-machine/automatic-ripping-machine#714] opened 2023-02-08 14:34 UTC
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

The wrong title is found resulting in wrong filenames since it's using the titlename.

This is perfect if the identification was correct but horribly wrong if this is incorrect.

For example I'm converting some UNSEEN CINEMA Dvds. It i=will try to find the title from "UNSEEN" which results in The World Unseen 2007 for all DVDs

### Describe the solution you'd like?

Better use the title of the DVD for the filenames which is "UNSEEN_CINEMA_AMATEUR".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment] 2023-02-08 23:20
I'm not sure if this is something that can be fixed. The auto online check is designed to be quite open/loose so that results can be found easier.

The online title searcher can be disabled via the `arm.yaml`

Setting `GET_VIDEO_TITLE: true` -> `GET_VIDEO_TITLE: false` Should disable any online queries and only use local data.

**Comment by sphaero** [comment] 2023-02-09 08:30
It's a bit double since it's convenient when a title is correctly found, but it's a hassle when it's incorrect. I think the search algorithm is trying every word in the title of the DVD? So if a title starts with "The" it will eventually search for "The" if it can't match anything? Didn't check in the code though.

**Comment by 1337-server** [comment] 2023-02-09 17:53
I will need to double-check, but I believe it checks the full title first with `_` replaced with spaces. Then, if no match, it will remove everything after the last space in a loop until it finds a match.

Is it not working as intended ?

**Comment by sphaero** [comment] 2023-02-10 08:34
It's done here, I think: 

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/56dfb69c7e1b91b91eb809bf30ec8fec928d5d74/arm/ripper/identify.py#L265-L280

I think it's working as intended depending on perspective. I noticed files are renamed if you change the title. Which is great news.

I'm working on converting an historic/educational archive. There's hardly any metadata available about those DVD's hence I end up with the weirdest titles.

**Comment by 1337-server** [comment] 2023-02-11 22:13
> I think it's working as intended depending on perspective. I noticed files are renamed if you change the title. Which is great news.

If it is, I'll close this. But if not just ping and ill re-open.

> I'm working on converting an historic/educational archive. There's hardly any metadata available about those DVD's hence I end up with the weirdest titles.

Good luck!

**Closed by 1337-server** 2023-02-11 22:13 UTC
Labels: enhancement
