### ISSUE TITLE
ARM Still Will not RIP Disk or create log file

### ISSUE THREAD

**Issue by poppab** [automatic-ripping-machine/automatic-ripping-machine#608] opened 2022-10-30 02:44 UTC
- [X ] I have checked the wiki
- [ ] I have searched for similar issues

**Describe the bug**
When I insert disk log created but nothing else happens. This is the same errors I got when using v 22.04.

**To Reproduce**
1.Insert Disk

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
* v2_master
* 
commit a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>
Date:   Mon Jun 27 18:31:48 2022 +0100

### Log file
No Log file create

I got this from /var/mail/arm file:Subject: Output from your job       73

To: arm@arm
Message-Id: <20221030023144.468FE13832F0@arm>
Date: Sat, 29 Oct 2022 22:31:44 -0400 (EDT)
From: arm <arm@arm>

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 443, in <module>
    running_jobs = db.session.query(Job).filter(Job.status.notin_(['fail', 'success']), Job.devpath == devpath).all()
  File "<string>", line 2, in query
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**When** executing command from command line get same error as when inserting DVD
arm@arm:/$ sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d **sr0**
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 443, in <module>
    running_jobs = db.session.query(Job).filter(Job.status.notin_(['fail', 'success']), Job.devpath == devpath).all()
  File "<string>", line 2, in query
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

This is the error in the empty.log file:

[29-10-2022 22:31:16] INFO ARM: Failed to open device /dev/nvme0n1p1 to check status.

**Comment by shitwolfymakes** [comment] 2022-10-30 18:09
Closing as duplicate of #596. Please follow the instructions in [this](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/596#issuecomment-1294280379) reply and respond there

**Closed by shitwolfymakes** 2022-10-30 18:09 UTC
Labels: bug
