### ISSUE TITLE
Ref #657, Ubuntu install script still broken

### ISSUE THREAD

**Issue by aiohdfgaiuhg** [automatic-ripping-machine/automatic-ripping-machine#658] opened 2023-01-14 00:40 UTC
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
Breaking hot-fix 2.6.10 unfortunately did not fix the issue.  I am now seeing a more simple error. 

when running script, I see 
failed due to runui.py.  When I run that python script manually i get the following. 

/opt/arm/arm/runui.py: 1: Main run page for armui: not found
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
/opt/arm/arm/runui.py: 6: Syntax error: word unexpected (expecting ")")

### Environment
Ubuntu 20.04.5LTS in Proxmox VM, new install
2.6.10 hot fix

**Comment by shitwolfymakes** [comment] 2023-01-14 00:52
Closing as duplicate of #592 

I'll try and duplicate this later, but I've never had this issue come up. May need to reimage and reinstall

**Closed by shitwolfymakes** 2023-01-14 00:52 UTC
Labels: bug
