### ISSUE TITLE
Data Disctype instead of Movie

### ISSUE THREAD

**Issue by staplemk** [automatic-ripping-machine/automatic-ripping-machine#386] opened 2021-01-04 02:35 UTC
### Description

The datatype is being misidentified as data, when it should be movie.  I successfully ripped the same DVD using my internal optical drive, however when I tried to use an external USB dvd drive (Samsung SE 218) I ran into this issue.

My DVD drive appears to be working just fine (I can play the DVD I am trying to rip with VLC).

Reviewed #245

### Environment
DISTRIB_ID = Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
Sorry, I dont know how to get this...but I just installed it yesterday.

### Log file
[WTRWLD_160972610605.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5762764/WTRWLD_160972610605.log)

**Comment by 1337-server** [comment] 2021-01-04 04:50
The error being output is a duplicate of #381

But im not sure why the disc is not being identified as movie

`Did not find valid dvd/bd files. Changing disctype to 'data'`

This means it cant find the folder `/VIDEO_TS` on the disc.

Can you post the structure of the dvd disk (the folder/files lists when you mount the disc), this may be something we can add to ARM.

**Comment by staplemk** [comment] 2021-01-04 17:46
I noticed the error message is equivalent to #381 as well, but that does not appear to be related to my issue.

Here is a screenshot of the DVD info:
![image](https://user-images.githubusercontent.com/76927546/103563410-19815f00-4e93-11eb-9f8c-ace64602a145.png)

Is that what you were looking for or is there another command I can give to provide more info?

**Comment by staplemk** [comment] 2021-01-04 17:51
Could this be an issue?  I am wanting to use sr1 (my external USB drive), but in the debug log I see this:

[2021-01-04 13:35:24] DEBUG ARM: main.log_udev_params DEVNAME:/dev/sr0
[2021-01-04 13:35:24] DEBUG ARM: main.log_udev_params DEVPATH:/devices/pci0000:00/0000:00:1f.2/ata3/host2/target2:0:0/2:0:0:0/block/sr0

**Comment by 1337-server** [comment] 2021-01-04 18:29
I completely missed this! You are correct, this issue appears to be that it is mounting the wrong drive.

Does the disc work if you mount and run ARM manually ?

The command is `/usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0 | at now`

**Comment by staplemk** [comment] 2021-01-04 19:39
Hey 1337-server, 

Thanks for your help!! I mounted and ran your command (except I used sr1) which led me to realize I had a typo in the etc/fstab:

![Screenshot from 2021-01-04 15-16-41](https://user-images.githubusercontent.com/76927546/103571688-b77c2600-4ea1-11eb-9ef7-7a9d38ff728a.png)

iso9660, not iso9600 :)

It is now identified correctly as a movie file, and ripping away!

**Closed** 2021-01-04 19:40 UTC
