### ISSUE TITLE
 Automatic Installation Script Appears broken across multiple installs (Debian, Ubuntu), manual installation also fails

### ISSUE THREAD

**Issue by aiohdfgaiuhg** [automatic-ripping-machine/automatic-ripping-machine#654] opened 2023-01-13 16:04 UTC
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
When installing using the Ubuntu 20.04 script, installation fails due to not creating home logs folder.  

After manual, 
mkdir /home/logs
sudo chown arm:arm /home/logs

the Ubuntu 20.04 script runs.  ARMUI service is running.  Upon Reboot, ARMUI is running, which is expected.  However, there is an error in the udev rules that do not invoke ARMUI when DVD inserted.  upon running manual command, 

sudo -u arm /usr/bin/python3 opt/arm/ripper/main.py -d sr6

ARMUI is invoked and ripping starts. 

Using default settings, MVK file made in transcode folder and then fails upon copy to the completed folder.

Using ARMUI settings file type mp4, logs detail mp4 fails to copy mp4 from transcode folder to raw folder with error "file doesn't exist" but it seems to be invoking the mkv file which wouldn't be in transcode.  

In addition, have tried,

sudo udevadm control --reload-rules 

with no improvement in script behavior after reload. 

Additionally, I erased disk and followed the wiki closely for install of Ubuntu 20.04 manual install, following all steps, and the same behavior as above is noticed.  

### Environment
Ubuntu 20.04.5 TLS in Proxmox VM with Sata controller passed through to VM, all disks accessible in MKV, noticed by script. 
2.6.9

___________________

**Describe the bug**
When installing using the Debian 11 script, installation fails due to not creating home logs folder.  

After manual, 
mkdir /home/logs
sudo chown arm:arm /home/logs

the Debian 11 script runs.  ARMUI service is running.  Upon Reboot, ARMUI is running, which is expected.  However, there is an error in the udev rules that do not invoke ARMUI when DVD inserted.  upon running manual command, 

sudo -u arm /usr/bin/python3 opt/arm/ripper/main.py -d sr6

ARMUI is invoked and ripping starts. 

Using default settings, MVK file made in transcode folder and then fails upon copy to the completed folder.

Using ARMUI settings file type mp4, logs detail mp4 fails to copy mp4 from transcode folder to raw folder with error "file doesn't exist" but it seems to be invoking the mkv file which wouldn't be in transcode.  

In addition, have tried,

sudo udevadm control --reload-rules 

with no improvement in script behavior after reload. 

Additionally, I erased disk and followed the wiki closely for install of Debian 11 manual install, following all steps, and the same behavior as above is noticed.  

### Environment
Debian 11 in Proxmox VM with Sata controller passed through to VM, all disks accessible in MKV, noticed by script. 
2.6.9

**Comment by shitwolfymakes** [comment] 2023-01-13 21:11
Discovered the root cause of this, will patch later today

**Comment by shitwolfymakes** [comment] 2023-01-13 22:57
Fixed by #655. Thanks!

**Closed by shitwolfymakes** 2023-01-13 22:57 UTC
Labels: bug, v2_devel, Ubuntu 20
