### ISSUE TITLE
🐛 MakeMKV says it is out of date

### ISSUE THREAD

**Issue by Moritz921** [automatic-ripping-machine/automatic-ripping-machine#1199] opened 2024-09-26 15:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

MakeMKV says it needs to be updated but it is already on the newest version (v1.17.7). When I run `makemkvcon -r info` inside the docker it throws an error:

```sh
# makemkvcon -r info
MSG:1005,0,1,"MakeMKV v1.17.7 linux(x64-release) started","%1 started","MakeMKV v1.17.7 linux(x64-release)"
DRV:0,1,999,0,"BD-RE HL-DT-ST BD-RE  WH16NS60 1.02 KLFL1BJ2227","","/dev/sr0"
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5021,131332,1,"This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.","This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.","http://www.makemkv.com/"
```

### To Reproduce

1. Pull the newest docker image
2. Run `docker-setup.sh`
3. Run `start_arm_container.sh`

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M. version:  2.8.1
Current git version: ac74406

### Expected behavior?

No error because of outdated version when on newest version.

### Relevant log output

```shell
[2024-09-26 11:24:56] INFO ARM: ARM version: 2.8.1
[2024-09-26 11:24:56] INFO ARM: Python version: 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]
[2024-09-26 11:24:56] INFO ARM: User is: arm
[2024-09-26 11:24:56] INFO ARM: Alembic head is: b326a3663939
[2024-09-26 11:24:56] INFO ARM: Database version is: b326a3663939
[2024-09-26 11:24:56] INFO ARM: ************* Starting ARM processing at 2024-09-26 11:24:56.304485 *************
[2024-09-26 11:24:57] INFO ARM: Looking for log files older than 1 days old.
[2024-09-26 11:24:57] INFO ARM: Checking path /home/arm/logs/ for old log files...
[2024-09-26 11:24:57] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[2024-09-26 11:24:57] INFO ARM: Job: SONIC_THE_HEDGEHOG_2
[2024-09-26 11:24:57] INFO ARM: Job #142 with PID 571 is currently running.
[2024-09-26 11:24:57] INFO ARM: Starting Disc identification
[2024-09-26 11:24:57] INFO ARM: Mounting disc to: /mnt/dev/sr0
[2024-09-26 11:24:57] INFO ARM: Mounting disc was successful
[2024-09-26 11:24:57] INFO ARM: Disc identified as video
[2024-09-26 11:24:57] INFO ARM: DVD CRC64 hash is: e2b505c9cef4c149
[2024-09-26 11:24:59] INFO ARM: Disc title Post ident -  title:Sonic-the-Hedgehog-2 year:2022 video_type:movie disctype: dvd
[2024-09-26 11:24:59] INFO ARM: We have no previous rips/jobs matching this label
[2024-09-26 11:24:59] INFO ARM: Waiting 60 seconds for manual override.
[2024-09-26 11:25:59] INFO ARM: ******************* Logging ARM variables *******************
[2024-09-26 11:25:59] INFO ARM: devpath: /dev/sr0
[2024-09-26 11:25:59] INFO ARM: mountpoint: /mnt/dev/sr0
[2024-09-26 11:25:59] INFO ARM: title: Sonic-the-Hedgehog-2
[2024-09-26 11:25:59] INFO ARM: year: 2022
[2024-09-26 11:25:59] INFO ARM: video_type: movie
[2024-09-26 11:25:59] INFO ARM: hasnicetitle: True
[2024-09-26 11:25:59] INFO ARM: label: SONIC_THE_HEDGEHOG_2
[2024-09-26 11:25:59] INFO ARM: disctype: dvd
[2024-09-26 11:25:59] INFO ARM: ******************* End of ARM variables *******************
[2024-09-26 11:25:59] INFO ARM: ******************* Logging config parameters *******************
[2024-09-26 11:25:59] INFO ARM: skip_transcode: True
[2024-09-26 11:25:59] INFO ARM: mainfeature: 0
[2024-09-26 11:25:59] INFO ARM: minlength: 900
[2024-09-26 11:25:59] INFO ARM: maxlength: 99999
[2024-09-26 11:25:59] INFO ARM: videotype: auto
[2024-09-26 11:25:59] INFO ARM: manual_wait: True
[2024-09-26 11:25:59] INFO ARM: manual_wait_time: 60
[2024-09-26 11:25:59] INFO ARM: ripmethod: mkv
[2024-09-26 11:25:59] INFO ARM: mkv_args: --profile=/etc/arm/config/eng_ger_spa_profile.xml
[2024-09-26 11:25:59] INFO ARM: delrawfiles: True
[2024-09-26 11:25:59] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[2024-09-26 11:25:59] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[2024-09-26 11:25:59] INFO ARM: hb_args_dvd: --subtitle scan -F
[2024-09-26 11:25:59] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[2024-09-26 11:25:59] INFO ARM: raw_path: /home/arm/media/raw/
[2024-09-26 11:25:59] INFO ARM: transcode_path: /home/arm/media/transcode/
[2024-09-26 11:25:59] INFO ARM: completed_path: /home/arm/media/completed/
[2024-09-26 11:25:59] INFO ARM: extras_sub: extras
[2024-09-26 11:25:59] INFO ARM: emby_refresh: False
[2024-09-26 11:25:59] INFO ARM: emby_server: 
[2024-09-26 11:25:59] INFO ARM: emby_port: 8096
[2024-09-26 11:25:59] INFO ARM: notify_rip: True
[2024-09-26 11:25:59] INFO ARM: notify_transcode: True
[2024-09-26 11:25:59] INFO ARM: max_concurrent_transcodes: 0
[2024-09-26 11:25:59] INFO ARM: ******************* End of config parameters *******************
[2024-09-26 11:25:59] INFO ARM: Checking for fstab entry.
[2024-09-26 11:25:59] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[2024-09-26 11:25:59] INFO ARM: Output directory "/home/arm/media/transcode/movies/Sonic-the-Hedgehog-2 (2022)" already exists.
[2024-09-26 11:25:59] INFO ARM: Final Output directory "/home/arm/media/transcode/movies/Sonic-the-Hedgehog-2 (2022)_172734989629"
[2024-09-26 11:25:59] INFO ARM: Output directory "/home/arm/media/completed/movies/Sonic-the-Hedgehog-2 (2022)" already exists.
[2024-09-26 11:25:59] INFO ARM: Final Output directory "/home/arm/media/completed/movies/Sonic-the-Hedgehog-2 (2022)_172734989629"
[2024-09-26 11:25:59] INFO ARM: Processing files to: /home/arm/media/transcode/movies/Sonic-the-Hedgehog-2 (2022)_172734989629
[2024-09-26 11:25:59] INFO ARM: ************* Ripping disc with MakeMKV *************
[2024-09-26 11:25:59] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-WaI15n3jLrzWU88y7liOljd7UIR0mormcZo2oO5xt_9CSj3Mg6mOxR1eUvU_CA569e
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[2024-09-26 11:26:00] INFO ARM: Starting MakeMKV rip. Method is mkv
[2024-09-26 11:26:01] INFO ARM: MakeMKV disc number: 0
[2024-09-26 11:26:01] INFO ARM: Destination is /home/arm/media/raw/Sonic-the-Hedgehog-2
[2024-09-26 11:26:01] INFO ARM: /home/arm/media/raw/Sonic-the-Hedgehog-2 exists.  Adding timestamp.
[2024-09-26 11:26:01] INFO ARM: raw_path is /home/arm/media/raw/Sonic-the-Hedgehog-2_172734989629
[2024-09-26 11:26:01] INFO ARM: Processing files to: /home/arm/media/raw/Sonic-the-Hedgehog-2_172734989629
[2024-09-26 11:26:01] INFO ARM: Using MakeMKV to get information on all the tracks on the disc. This will take a few minutes...
[2024-09-26 11:26:02] ERROR ARM: Call to MakeMKV failed with code: 253 (b'MSG:1005,0,1,"MakeMKV v1.17.7 linux(x64-release) started","%1 started","MakeMKV v1.17.7 linux(x64-release)"\nDRV:0,2,999,1,"BD-RE HL-DT-ST BD-RE  WH16NS60 1.02 KLFL1BJ2227","SONIC_THE_HEDGEHOG_2","/dev/sr0"\nDRV:1,256,999,0,"","",""\nDRV:2,256,999,0,"","",""\nDRV:3,256,999,0,"","",""\nDRV:4,256,999,0,"","",""\nDRV:5,256,999,0,"","",""\nDRV:6,256,999,0,"","",""\nDRV:7,256,999,0,"","",""\nDRV:8,256,999,0,"","",""\nDRV:9,256,999,0,"","",""\nDRV:10,256,999,0,"","",""\nDRV:11,256,999,0,"","",""\nDRV:12,256,999,0,"","",""\nDRV:13,256,999,0,"","",""\nDRV:14,256,999,0,"","",""\nDRV:15,256,999,0,"","",""\nMSG:5021,131332,1,"This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.","This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.","http://www.makemkv.com/"\n')
[2024-09-26 11:26:02] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[2024-09-26 11:26:02] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 214, in get_track_info
    mkv = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r --progress=/home/arm/logs/progress/142.log --messages=-stdout --minlength=900 --cache=1 info disc:0
' returned non-zero exit status 253.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 69, in makemkv
    get_track_info(mdisc, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 220, in get_track_info
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 213, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[2024-09-26 11:26:02] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

According to https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224 version 1.17.7 is the newest version. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment] 2024-10-04 23:04
This is a duplicate of #1195

**Closed** 2024-10-04 23:05 UTC
Labels: bug
