### ISSUE TITLE
MakeMKVCon failing with Bluray discs

### ISSUE THREAD

**Issue by jeffminton** [automatic-ripping-machine/automatic-ripping-machine#674] opened 2023-01-20 23:35 UTC
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Bluray discs are failing to rip in the makemkvcon stage of the ripping process, DVDs are ripping properly. The makemkvcon process fails with the fiollowing messages from the logs.

MSG:5010,0,0,"Failed to open disc","Failed to open disc"
[01-20-2023 22:51:45] ERROR ARM: makemkv.__init__ Call to MakeMKV failed with code: 11 (b'')

I have tested makemkvcon installed separately on my ubuntu server and it is able to load and rip the disc fine.

**To Reproduce**
1. Insert bluray disc
2. Ripping process starts
3. Ripping process fails at initial makemkv step

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

Arm Version: 2.6.10 Docker Image

### Log file
[GUARDIANS_OF_THE_GALAXY_VOL_2_167425501498.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10470949/GUARDIANS_OF_THE_GALAXY_VOL_2_167425501498.log)

**Comment by jeffminton** [comment] 2023-01-23 20:25
I noticed that in the output also and thought it might be the issue. Before testing again I had already pulled down the most recent docker image. I am pulling from this docker repo automaticrippingmachine/automatic-ripping-machine and the image I am running has this id sha256:0513fe982ae0e0af2b0496b6a523a673a06848a943dbb03f6c8ad3ce315fdc13.

As far as I can tell I am running the most recent docker image

**Comment by shitwolfymakes** [comment] 2023-01-25 19:21
If using the docker, make sure you've pulled the `v2_devel` tag. I don't know if the functionality added in 1337-server/automatic-ripping-machine#161 has been merged into it yet

**Comment by jeffminton** [comment] 2023-01-26 19:14
I was able to get it working on the v2_devel tag. Not sure if I needed that tag or not but I found a reference to the MAKEMKV_APP_KEY environment variable. I added that and the most resent makemkv key to my docker compose and it appears to be working now

**Comment by joelishness** [comment] 2023-01-27 20:50
I resolved a similar issue by changing from `latest` to `v2_devel`

Was working fine yesterday, then not working today.
I did NOT see evaluation expired errors, but I updated the key anyway with:
```
#!/usr/bin/env bash

# This script is inspired by the script posted on the forums.
# Given that it hasn't been taken down I'm going to assume they
# don't have a problem with users programmatically scraping the
# beta key.
# Link: https://forum.makemkv.com/forum/viewtopic.php?p=119221#p119221

makemkv_serial_url="https://forum.makemkv.com/forum/viewtopic.php?f=5&t=1053"
makemkv_serial=$(curl -fsSL "$makemkv_serial_url" | grep -oP 'T-[\w\d@]{66}')
echo "MakeMKV beta key for this month: $makemkv_serial"

echo "app_Key = \"$makemkv_serial\"" > /arm/.MakeMKV/settings.conf

```
(script modified for my path)

It still did not produce evaluation errors, yet still error occurred.

So dropping the log here in case it is useful for some other reason
[STAR_TREK_TNG_S1_D6_167485149584.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10523059/STAR_TREK_TNG_S1_D6_167485149584.log)

**Comment by shitwolfymakes** [comment] 2023-02-03 00:33
Unfortunately the documentation for makemkvcon error codes is almost nonexistant, so there's little we can do there. Try cleaning the disk?

**Comment by 1337-server** [comment] 2023-02-03 07:07
It looks like there is a double space in the run command for MakeMKV

`makemkvcon mkv  -r --progress=-stdout --messages=-stdoutdev:/dev/sr0 0 '/home/arm/media/raw/Star Trek- The Next Generation_167485149584' --minlength=600>> /home/arm/logs/STAR_TREK_TNG_S1_D6_167485149584.log
`

This may be the cause, as error code 1 means the Linux command failed.

The double space in between the `mkv` and the `-r`

**Comment by 1337-server** [comment] 2023-02-14 03:05
Issue should be resolved.

**Closed by 1337-server** 2023-02-14 03:05 UTC
Labels: bug
