### ISSUE TITLE
🐛 Blue Ray Drive ejects Disk immediately and Drive blinks rapidly 

### ISSUE THREAD

**Issue by JazzX** [automatic-ripping-machine/automatic-ripping-machine#779] opened 2023-03-05 20:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The drive is a Pioneer BDR-US04 USB3 Blu-ray Drive, that works normally with Make MKV and handbrake. 
If I use The ARM Docker the Drive blinks rapidly and ejects the disk. My other USB DVD Drive works normally with ARM.
I've checked the Docker log for the arm container and it shows that arm gives the drive no time to check if there is a valid disk in the drive and sends an eject command to the Drive.
This happens even if there is no Disk in the drive.
The Host OS is Ubuntu 22.04 with all the Updates.
sr0 is the working DVD Drive. The same Problem happens if i only use the Blu Ray Drive.

### To Reproduce

Use ARM Docker with this Drive on an Ubuntu 22.04 host OS.

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

Python version: 3.8.10
A.R.M version: 2.6.18
Current git version:
0813a111d520f9f2f8e702e42026462519e2e8d8

### Expected behavior?

Arm should give the Drive the time to Check for a Disk.

### Relevant log output

```shell
Mar  5 20:20:51 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:51 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:51 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:51 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:51 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:51 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:51 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:53 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:53 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:53 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:53 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:53 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:53 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:53 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:53 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:53 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Mar  5 20:20:54 18523c3f53d2 ARM: Entering docker wrapper
Mar  5 20:20:54 18523c3f53d2 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aczietlow** [comment] 2023-03-20 00:27
I'm having the exact same error with Ubuntu 22.04 and the Pioneer BDR-XD07UHD. The drive worked fine when I tested on the host machine, but as soon as I run the ARM docker container, I experience the same behavior.

Is there anything more in syslog?  Below is the output I'm seeing when experiencing the same behavior.

```
Mar 19 20:13:06 k8s kernel: [103444.794059] sr 6:0:0:0: ioctl_internal_command return code = 2
Mar 19 20:13:06 k8s kernel: [103444.794072] sr 6:0:0:0: Sense Key : Hardware Error [current] 
Mar 19 20:13:06 k8s kernel: [103444.794080] sr 6:0:0:0: Add. Sense: Media load or eject failed
Mar 19 20:13:06 k8s kernel: [103444.798603] systemd-udevd[4639]: sr1: Process '/sbin/setuser arm /opt/arm/scripts/docker/docker_arm_wrapper.sh sr1' failed with exit code 1.
```

**Comment by JazzX** [comment] 2023-03-20 07:51
I did not find a workaround. I waited for a reply and used the working dvd drive and startet with my dvds.

**Comment by shitwolfymakes** [comment] 2023-03-22 20:30
Is your drive plugged into a USB 3.0 or newer port? If not that might be the issue.

**Comment by JazzX** [comment] 2023-03-24 08:57
Yes i it was plugged into an USB 3.0 Port (blue Port, marked with the USB3.0 SuperSpeed Icon). 
The Drive Works on the same pc and port flawless without ARM. I have taken a quick look into the ARM Code, and I think the problem is with the drive error check, there needs to be a wait time but to do this the drive monitoring might have to get its own thread or the whole arm looks up as it waits for the drive.

**Comment by martini1992** [comment] 2023-04-12 05:22
I'm having the same issue with a Pioneer BDR-UD03 over USB2 using the docker container on Debian stable. Drive works fine while ARM isn't running.

**Comment by grimkroton** [comment] 2023-05-08 07:53
Something new here? Hitting the same bug with docker v2.6.29

**Comment by Tjkent88** [comment] 2023-05-18 23:42
820 is a duplicate of this ticket.

**Comment by BaelfireNightshd** [comment] 2023-05-19 03:20
What information is needed to help figure out this issue? I have the same issue with a Pioneer BDR-XD08UMB-S. Also having this problem with the docker image.

**Comment by TallPatrick** [comment] 2023-05-19 06:14
I can also reproduce this issue.
I have a Pioneer BDR-XS07UHD Blu Ray drive.

For me, this issue happens any time that ARM ejects a disk.  I'm able to force the disk back in, but that doesn't seem good for the drive.

I also am able to stop the repeated ejecting by unplugging and replugging the drive, but this makes it unusable by ARM in the docker container.

**Comment by Tjkent88** [comment] 2023-05-19 16:47
The only way I have gotten it to stop is to restart the container, but that is kinda against the point. 

Does anyone else have a similar environment?
I'm running this on a proxmox vm in a docker container.

**Comment by microtechno9000** [comment] 2023-05-19 21:44
I setup my system with a VM and docker to try and replicate this issue and havent been able to.

I updated the Wiki with the VM config setup, maybe hat might help?

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Getting-Started#Virtual-Machine-Setup

**Comment by TallPatrick** [comment] 2023-05-20 05:27
@microtechno9000 , it looks like everyone else in this thread with this issue has a pioneer blu-ray drive.  I would be willing to bet it is something specific about those drives.

**Comment by microtechno9000** [comment] 2023-05-20 05:52
Interesting, I am on my phone so can't see all the posts. If it isn't already listed could you post the lspci -v details from a drive.

See what info can be dug up, maybe there is some special handling required.

**Comment by TallPatrick** [comment] 2023-05-20 06:57
None of these are screaming out at me as the disk drive
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/32583806/508dfe39-d372-454d-8e1c-fccfb626cd1a)

**Comment by BaelfireNightshd** [comment] 2023-05-20 06:59
Output of `sudo lsscsi -vg`

```
dir: /sys/bus/scsi/devices/10:0:0:1  [/sys/devices/pci0000:00/0000:00:08.1/0000:0a:00.3/usb5/5-4/5-4:1.0/host10/target10:0:0/10:0:0:1]
[11:0:0:0]   cd/dvd  PIONEER  BD-RW  BDR-XD08U 1.00  /dev/sr0   /dev/sg2
```

Output of `sudo lspci -v` though I don't think it'll be useful. 

```
0a:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1 (prog-if 30 [XHCI])
        Subsystem: Hewlett-Packard Company Raven USB 3.1
        Flags: bus master, fast devsel, latency 0, IRQ 66, IOMMU group 1
        Memory at b0300000 (64-bit, non-prefetchable) [size=1M]
        Capabilities: [48] Vendor Specific Information: Len=08 <?>
        Capabilities: [50] Power Management version 3
        Capabilities: [64] Express Endpoint, MSI 00
        Capabilities: [a0] MSI: Enable- Count=1/8 Maskable- 64bit+
        Capabilities: [c0] MSI-X: Enable+ Count=8 Masked-
        Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
```

`sudo lsusb -v -s 7:3`
```
Bus 007 Device 003: ID 08e4:017a Pioneer Corp. Pioneer Blu-ray Drive
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         9
  idVendor           0x08e4 Pioneer Corp.
  idProduct          0x017a 
  bcdDevice            1.00
  iManufacturer           1 Pioneer Corporation
  iProduct                2 Pioneer Blu-ray Drive
  iSerial                 3 1452060912801018
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x002c
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower                8mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      2 SFF-8020i, MMC-2 (ATAPI)
      bInterfaceProtocol     80 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
Binary Object Store Descriptor:
  bLength                 5
  bDescriptorType        15
  wTotalLength       0x0016
  bNumDeviceCaps          2
  USB 2.0 Extension Device Capability:
    bLength                 7
    bDescriptorType        16
    bDevCapabilityType      2
    bmAttributes   0x00000002
      HIRD Link Power Management (LPM) Supported
  SuperSpeed USB Device Capability:
    bLength                10
    bDescriptorType        16
    bDevCapabilityType      3
    bmAttributes         0x00
    wSpeedsSupported   0x000e
      Device can operate at Full Speed (12Mbps)
      Device can operate at High Speed (480Mbps)
      Device can operate at SuperSpeed (5Gbps)
    bFunctionalitySupport   1
      Lowest fully-functional device speed is Full Speed (12Mbps)
    bU1DevExitLat           0 micro seconds
    bU2DevExitLat           0 micro seconds
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered
```

If there's any useful commands I can run for you let me know. I tried to guess at some that might be more useful than the one you asked for.

**Comment by BaelfireNightshd** [comment] 2023-05-20 07:09
> None of these are screaming out at me as the disk drive
> 
> ![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/32583806/508dfe39-d372-454d-8e1c-fccfb626cd1a)
> 
> 
> 
> 

If your drive is USB I don't think much will show in lspci since as far as pci is concerned it just sees the controllers and hubs.

**Comment by 1337-server** [comment] 2023-05-20 07:26
Are you passing in both sr0 and sg2 to the container ?

**Comment by TallPatrick** [comment] 2023-05-20 07:28
> If your drive is USB I don't think much will show in lspci

correct.  my drive is USB.  My output of lsusb -v is remarkably similar to @BaelfireNightshd 



> Are you passing in both sr0 and sg2 to the container ?

I have ARM running in a debian Proxmox VM.  I'm passing through the USB port where I have the blu-ray drive plugged in.

**Comment by TallPatrick** [comment] 2023-05-20 07:34
here's my output of lsusb:
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/32583806/6837ff70-d7db-437f-8680-40f89356159e)
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/32583806/ef8541f6-c9e1-4aac-b504-6870ddc88187)

**Comment by 1337-server** [comment] 2023-05-20 16:19
> Are you passing in both sr0 and sg2 to the container ?
> 
> I have ARM running in a debian Proxmox VM. I'm passing through the USB port where I have the blu-ray drive plugged in.

So bare-metal ?

Proxmod and MakeMKV, as far as I'm aware, do not play well together.
It's been a while since I've checked, but both proxmox and MakeMKV had issues in their forums about this. It might have changed since then.

It may be worth a look on those forums ?

**Comment by JazzX** [comment] 2023-05-20 16:47
Like stated in my initial post the problem happens on a bare metal installation. 
The issue is that not all drives  behave equal and with some drives arm thinks the disk is invalid, while the drive has not even initialized the medium, arm needs to wait some time after the drive is closed and then check if there is an valid disk in the drive. 


I am not to proficient with python, but I took a glimpse over the relevant code part and i think the problem with fixing this problem is that this code is part of the main loop of arm so slapping a wait in there would lock up the hole arm. To fix it arm has to be reworked so that the drive checks can be asynchron to the main arm code.

**Comment by 1337-server** [comment] 2023-05-20 17:07
I just had a quick look around `scripts/thickclient/arm_wrapper.sh` and it looks like a sleep/wait has been removed. There used to be a 5/10 second wait, I can't remember which, but it's been removed.

You may want to try adding it back there and see if that solves the issue.

**Comment by BaelfireNightshd** [comment] 2023-05-20 17:30
> Are you passing in both sr0 and sg2 to the container ?
> 
> Can you also share your full docker run command ?
> 
> Have you tried adding `--cap-add SYS_RAWIO` ? As with usb drives, this is sometimes required to get full speed.

Here is my start_arm_container.sh
```
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1006" \
    -e ARM_GID="1007" \
    -v "/home/arm:/home/arm" \
    -v "/media/jellyfin/arm/music:/home/arm/Music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/media/jellyfin/arm:/home/arm/media" \
    -v "/media/jellyfin/movies:/home/arm/media/completed/movies" \
    -v "/media/jellyfin/shows:/home/arm/media/completed/shows" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sg2:/dev/sg2" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest
```

I haven't tried adding `--cap-add SYS_RAWIO` yet. I assume it would just in with the rest of the flags above. 

Also, I'm running my docker container on bare metal linux. No VMs.

**Comment by BaelfireNightshd** [comment] 2023-05-20 17:54
> I just had a quick look around `scripts/thickclient/arm_wrapper.sh` and it looks like a sleep/wait has been removed. There used to be a 5/10 second wait, I can't remember which, but it's been removed.
> 
> You may want to try adding it back there and see if that solves the issue.
> 
> EDIT: This was version: 2.2 https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/2.2/scripts/arm_wrapper.sh

Just tried it. Didn't make a difference. 
arm_wrapper.sh
```
#!/bin/bash -i

set -eo pipefail

# added to try to fix the ejecting bug
sleep 5

DEVNAME=$1
PROTECTION=""
USER="arm"

#######################################################################################
# YAML Parser to read Config
#
# From: https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script
#######################################################################################

function parse_yaml {

...
```

**Comment by TallPatrick** [comment] 2023-05-31 05:42
I have found a work-around for anyone having this issue.  If you want the drive to stop repeatedly ejecting, simply insert a disk and then manually eject by hitting the eject button on the drive.  It's non-ideal, but it'll at least make it less likely for a motor to burn out.

**Comment by JazzX** [comment] 2023-05-31 08:09
On my Drive this does not work, the only thing is to leave the drive open or disconnect it.

**Comment by microtechno9000** [comment] 2023-05-31 08:11
If the ARM docker is not running does this cause the same issues?

With the arm docker not running, does the command line eject call work as expected?

**Comment by JazzX** [comment] 2023-05-31 08:13
Without ARM running the drive works without a flaw on the system and the OS, like i have written in my initial post.

**Comment by Tjkent88** [comment] 2023-06-08 02:58
I don't have the docker container set up but I don't think that the issue is drive related, I have the ubuntu installation on a thinkcenter M700 and it works flawlessly.

**Comment by tetriskillerh** [comment] 2023-07-06 09:42
I have a issue that is kind of the same. It worked fine until i got to  some dvds that are aparently "Not CD, Blu-ray, DVD or Data."
but thar are movies. Some other disc work fine and some dont but on an diferent pc they work with no problem.

**Comment by microtechno9000** [comment] 2023-07-06 09:51
what do you mean, movies?

**Comment by tetriskillerh** [comment] 2023-07-06 09:55
Marvel's Avangers is a Movie
Thor is a Movie
Captain America The First Avenger is a Movie

Or am i wrong.

**Comment by tetriskillerh** [comment] 2023-07-06 10:03
I don't get anything it just takes the disk and prints out the lines in the arm.log. no logs fore the disk it self.

**Comment by microtechno9000** [comment] 2023-07-06 11:09
are you able to edit the arm_wrapper, if so on line 68, comment out the exit

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/scripts/thickclient/arm_wrapper.sh#L68

**Comment by tetriskillerh** [comment] 2023-07-06 11:13
where is the file stored?

**Comment by microtechno9000** [comment] 2023-07-06 11:28
will need to enter the docker container 
`$ docker exec -it automatic-ripping-machine /bin
/bash`


edit the file in scripts
`/opt/arm/scripts/docker/docker_arm_wrapper.sh`

The file for docker is in a different location, https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/scripts/docker/docker_arm_wrapper.sh#L64

**Comment by tetriskillerh** [comment] 2023-07-06 11:55
Well maybe i'm stupid but after executing this command

sudo docker exec -it arm-rippers /bin /bash

i get this

failed: exec failed: unable to start container process: exec: "/bin": permission denied: unknown

the same without sudo

**Comment by microtechno9000** [comment] 2023-07-06 12:09
no, my bad, there should be no space between /bin/bash

**Comment by tetriskillerh** [comment] 2023-07-06 12:12
i was able to do it with portainer but nothin changed  i rebootet the system but still 1:disk in 2:spin up 3:disk out
and no log for the disk

**Comment by TallPatrick** [comment] 2023-07-06 17:49
@microtechno9000 
I made the modification you suggested above on my docker container and while it didn't fix the issue, it did make my DVD drive seem to spam "eject" about half as often (rather than hearing the eject motors every second, it was every other second).  So an improvement, but there's something else at play still.

**Comment by microtechno9000** [comment] 2023-07-06 22:28
> @microtechno9000 
> I made the modification you suggested above on my docker container and while it didn't fix the issue, it did make my DVD drive seem to spam "eject" about half as often (rather than hearing the eject motors every second, it was every other second).  So an improvement, but there's something else at play still.

interesting, will have to look in more detail over the weekend

**Comment by microtechno9000** [comment] 2023-07-08 12:14
Had a look, it is much easier on a pc/laptop than on a phone

The docker version of the arm_wrapper attempts to eject any unidentified cd/dvd/bluray then exits, so in addition to line 64 you should also comment out 63, otherwise the drive will try to eject and then start a job with ARM

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/scripts/docker/docker_arm_wrapper.sh#L63-L64

I have made changes to the files on my fork, and will test it out over the next few days also.
https://github.com/microtechno9000/automatic-ripping-machine/tree/bugfix_ejects

**Comment by TallPatrick** [comment] 2023-07-08 14:07
@microtechno9000 , going to give this a try on my install and see how it works.  I'll report back with more information.

**Comment by Kylespamaccoun7** [comment] 2023-07-08 16:06
Hi, I have a nearly identical issue and have been following the thread for the past few days. I installed ARM again from scratch on a new VM Tuesday, with the same exact result. I get one good rip post-install from each drive. Subsequent discs of any type are rejected by each after about 10 seconds. Before the disc is bailed out, I can see and open the files on audio, dvd, and data discs @microtechno9000 's fork wasn't successful for me.

My logs after my first and second install look identical to those posted above.

**Comment by TallPatrick** [comment] 2023-07-08 20:52
@microtechno9000 been testing with the two lines commented out on my install and after about 5 discs I can say the issue isn't happening anymore.

I am still seeing issues where a disc will get automatically ejected upon insertion before anything shows up in ARM, but I have yet to test and see if it's a hardware issue (but I'm thinking it isn't).

**Comment by rjgould** [comment] 2023-07-16 22:48
> Had a look, it is much easier on a pc/laptop than on a phone
> 
> The docker version of the arm_wrapper attempts to eject any unidentified cd/dvd/bluray then exits, so in addition to line 64 you should also comment out 63, otherwise the drive will try to eject and then start a job with ARM
> 
> https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/scripts/docker/docker_arm_wrapper.sh#L63-L64
> 
> I have made changes to the files on my fork, and will test it out over the next few days also. https://github.com/microtechno9000/automatic-ripping-machine/tree/bugfix_ejects

Just had this issue, I found just commenting out line 63 seemed to stop this happening.

**Comment by martini1992** [comment] 2023-09-01 16:23
> > Had a look, it is much easier on a pc/laptop than on a phone
> > The docker version of the arm_wrapper attempts to eject any unidentified cd/dvd/bluray then exits, so in addition to line 64 you should also comment out 63, otherwise the drive will try to eject and then start a job with ARM
> > https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/09443809d329deda0265f86df725cbe954714b68/scripts/docker/docker_arm_wrapper.sh#L63-L64
> > 
> > I have made changes to the files on my fork, and will test it out over the next few days also. https://github.com/microtechno9000/automatic-ripping-machine/tree/bugfix_ejects
> 
> Just had this issue, I found just commenting out line 63 seemed to stop this happening.

Can confirm commenting out just the eject command (63) allows ripping to begin. The drive also successfully ejected when ripping was complete.

**Closed** 2023-09-24 21:44 UTC
Labels: bug
